version: '3.9'

services:
  web:
    image: ghcr.io/samnangnhum/axion-trade-web:latest
    container_name: axion-trade-web
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose port 3000 for Next.js
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL="http://109.123.235.57:1337" # Replace with your backend URL
