import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { dir } from "i18next";
import { siemreap, openSans, notoSans } from "@/assets/Fonts";
import { languages } from "../i18n/settings";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({
  children,
  params = { lng: "en" }, // Default fallback for lng
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  const languageClass =
    params.lng === "km"
      ? siemreap.className
      : params.lng === "en"
      ? openSans.className
      : notoSans.className;

  return (
    <html lang={params.lng} dir={dir(params.lng)}>
      <body className={languageClass} style={{ fontSize: "16px" }}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
